# ============================================================
# 3. 게임 속도 버튼
# 재생/일시정지 버튼과 배속 버튼 위치/크기 설정
# ============================================================

PlayPauseButtonSize         = 110
PlayPauseButtonOffsetX      = 18
PlayPauseButtonOffsetY      = -20
PlayPauseButtonBottomMargin = 18
SpeedMultiplierButtonSize         = 70
SpeedMultiplierButtonOffsetX      = 138
SpeedMultiplierButtonOffsetY      = -27
SpeedMultiplierButtonBottomMargin = 18
