#pragma once

namespace UIConfig
{
    // ── 상단 상태바 ──────────────────────────────────────────
    extern float StatusBarX;
    extern float StatusBarY;
    extern float StatusBarHeight;
    extern float StatusBarPaddingX;
    extern float StatusBudgetBlockWidth;
    extern float StatusNpcBlockWidth;
    extern float StatusSupportBlockWidth;
    extern float StatusBlockGap;
    extern float StatusIconSize;
    extern float StatusIconTextGap;
    extern float StatusLabelOffsetY;
    extern float StatusValueOffsetY;
    extern float StatusLabelHeight;
    extern float StatusValueHeight;
    extern float StatusLabelFontSize;
    extern float StatusValueFontSize;

    extern float BudgetBlockOffsetX;
    extern float BudgetBlockOffsetY;
    extern float NpcBlockOffsetX;
    extern float NpcBlockOffsetY;
    extern float SupportBlockOffsetX;
    extern float SupportBlockOffsetY;

    // ── 하단 좌측 패널 ───────────────────────────────────────
    extern float SpeedPanelX;
    extern float SpeedPanelWidth;
    extern float SpeedPanelHeight;
    extern float SpeedPanelBottomMargin;
    extern float SpeedPanelMinY;
    extern float PanelTextOffsetX;
    extern float TimeBarOffsetY;
    extern float TimeBarWidth;
    extern float TimeBarHeight;
    extern float DateTextOffsetY;
    extern float DateTextWidth;
    extern float DateTextHeight;
    extern float DateFontSize;

    // ── 게임 속도 버튼 ───────────────────────────────────────
    extern float PlayPauseButtonSize;
    extern float PlayPauseButtonOffsetX;
    extern float PlayPauseButtonOffsetY;
    extern float PlayPauseButtonBottomMargin;
    extern float SpeedMultiplierButtonSize;
    extern float SpeedMultiplierButtonOffsetX;
    extern float SpeedMultiplierButtonOffsetY;
    extern float SpeedMultiplierButtonBottomMargin;

    // ── 하단 메뉴 아이콘 버튼 ────────────────────────────────
    extern float MenuButtonSize;
    extern float MenuButtonGap;
    extern float MenuMinScaleFactor;

    // ── 게임 오버 팝업 ───────────────────────────────────────
    extern float GameOverPanelWidth;
    extern float GameOverPanelHeight;
    extern float GameOverTitlePaddingX;
    extern float GameOverTitleOffsetY;
    extern float GameOverTitleHeight;
    extern float GameOverBodyPaddingX;
    extern float GameOverBodyOffsetY;
    extern float GameOverBodyBottomPadding;

    // ── 칙령 UI ──────────────────────────────────────────────
    extern float EdictHeaderTopPadding;
    extern float EdictHeaderHeight;
    extern float EdictHorizontalMargin;
    extern float EdictVerticalMargin;
    extern float EdictGridFrameHeight;
    extern float EdictGridGapFromHeader;
    extern float EdictDetailGapFromGrid;
    extern float EdictTitleFontSize;
    extern float EdictCategoryWidth;
    extern float EdictCategoryHeight;
    extern float EdictCategoryGap;
    extern float EdictSlotPaddingLeft;
    extern float EdictSlotPaddingTop;
    extern float EdictSlotGapX;
    extern float EdictSlotGapY;
    extern float EdictDetailTitleFontSize;
    extern float EdictDetailCostFontSize;
    extern float EdictTitleTextOffsetX;
    extern float EdictTitleTextOffsetY;
    extern float EdictSlotTextOffsetX;
    extern float EdictSlotTextOffsetY;
    extern float EdictDetailTitleOffsetX;
    extern float EdictDetailTitleOffsetY;
    extern float EdictDetailCostRowWidth;
    extern float EdictDetailCostRowOffsetX;
    extern float EdictDetailCostRowOffsetY;
    extern float EdictDetailCostIconSize;
    extern float EdictDetailCostIconOffsetX;
    extern float EdictDetailCostIconOffsetY;
    extern float EdictDetailCostOffsetX;
    extern float EdictDetailCostOffsetY;
    extern float EdictDetailCostTextWidth;
    extern float EdictDetailCostTextHeight;
    extern bool EdictDetailInfoInlineWithCost;
    extern float EdictDetailInfoInlineGapX;
    extern float EdictDetailInfoPanelOffsetX;
    extern float EdictDetailInfoPanelOffsetY;
    extern float EdictDetailInfoPanelWidthAdjust;
    extern float EdictDetailInfoPanelHeightAdjust;
    extern float EdictDetailInfoTextWidth;
    extern float EdictDetailInfoTextHeight;
    extern float EdictDetailInfoOffsetX;
    extern float EdictDetailInfoOffsetY;
    extern float EdictFeedbackOffsetX;
    extern float EdictFeedbackOffsetY;
    extern float EdictDetailBodyOffsetX;
    extern float EdictDetailBodyOffsetY;
    extern float EdictRequirementOffsetX;
    extern float EdictRequirementOffsetY;
    extern float EdictApplyButtonOffsetX;
    extern float EdictApplyButtonOffsetY;
    extern float EdictApplyButtonTextOffsetX;
    extern float EdictApplyButtonTextOffsetY;
    extern float EdictTaxPolicyTitleOffsetX;
    extern float EdictTaxPolicyTitleOffsetY;
    extern float EdictTaxPolicyRowTextOffsetX;
    extern float EdictTaxPolicyRowTextOffsetY;
    extern float EdictTaxPolicySummaryOffsetX;
    extern float EdictTaxPolicySummaryOffsetY;
    extern float EdictApplyButtonWidth;
    extern float EdictApplyButtonHeight;
    extern float EdictScrollTrackWidth;
    extern float EdictCloseButtonSize;
    extern bool EdictEnableTaxPolicyPanel;
    extern float EdictTaxPolicyPanelWidth;
    extern float EdictTaxPolicyPanelHeight;
    extern float EdictTaxPolicySummaryHeight;

    // ── 연감 UI ──────────────────────────────────────────────
    extern float AlmanacPanelWidth;
    extern float AlmanacPanelHeight;
    extern float AlmanacPanelTopOffset;
    extern float AlmanacHeaderHeight;
    extern float AlmanacHeaderPadding;
    extern float AlmanacRibbonTopOffset;
    extern float AlmanacFrameInsetX;
    extern float AlmanacFrameHeaderOverlap;
    extern float AlmanacFrameBottomInset;
    extern float AlmanacRailLeftInset;
    extern float AlmanacRailTopInset;
    extern float AlmanacRailBottomInset;
    extern float AlmanacRailThumbTopOffset;
    extern float AlmanacRailThumbMinHeight;
    extern float AlmanacRailThumbExpand;
    extern float AlmanacRailToContentGap;
    extern float AlmanacContentMarginX;
    extern float AlmanacContentMarginTop;
    extern float AlmanacContentMarginBottom;
    extern float AlmanacContentTopInset;
    extern float AlmanacContentBottomInset;
    extern float AlmanacTabSize;
    extern float AlmanacTabGap;
    extern float AlmanacTabBaseOffsetY;
    extern float AlmanacTabSelectedOffsetY;
    extern float AlmanacTitleFontSize;
    extern float AlmanacTitlePaddingX;
    extern float AlmanacTitlePaddingY;
    extern float AlmanacCloseButtonSize;
    extern float AlmanacCloseButtonOffsetX;
    extern float AlmanacCloseButtonOffsetY;
    extern float AlmanacMetricRowHeight;
    extern float AlmanacMetricRowGap;
    extern float AlmanacDetailRowHeight;
    extern float AlmanacDetailRowGap;
    extern float AlmanacCardColumns;
    extern float AlmanacCardGapX;
    extern float AlmanacCardGapY;
    extern float AlmanacLeftPanelRatio;
    extern float AlmanacPageColumnGap;
    extern float AlmanacWidePageColumnGap;
    extern float AlmanacPageTitleHeight;
    extern float AlmanacPageFrameTop;
    extern float AlmanacOffscreenHideOffset;

    // ── 건물 선택 UI ─────────────────────────────────────────
    extern float BuildingPanelWidthRatio;
    extern float BuildingPanelMinWidth;
    extern float BuildingPanelMaxWidth;
    extern float BuildingPanelTopOffset;
    extern float BuildingPanelBottomMargin;
    extern float BuildingPanelRightInset;
    extern float BuildingPanelMinHeight;
    extern float BuildingPanelInnerMarginX;
    extern float BuildingPanelInnerMarginTop;
    extern float BuildingPanelInnerBottomInset;
    extern float BuildingTabWidth;
    extern float BuildingTabHeight;
    extern float BuildingTabGap;
    extern float BuildingTabLabelFontSize;
    extern float BuildingTabLabelOffsetX;
    extern float BuildingTabLabelOffsetY;
    extern float BuildingTitleFontSize;
    extern float BuildingSubtitleFontSize;
    extern float BuildingBodyFontSize;
    extern float BuildingPageTitleFontSize;
    extern float BuildingBudgetTextFontSize;
    extern float BuildingOverviewWorkModeLabelFontSize;
    extern float BuildingOverviewWorkModeValueFontSize;
    extern float BuildingOverviewBudgetLabelFontSize;
    extern float BuildingOverviewBudgetValueFontSize;
    extern float BuildingOverviewOccupancyLabelFontSize;
    extern float BuildingOverviewOccupancyValueFontSize;
    extern float BuildingOverviewMetricLabelFontSize;
    extern float BuildingOverviewMetricSectionHeaderFontSize;
    extern float BuildingOverviewMetricValueFontSize;
    extern float BuildingUpgradeTitleFontSize;
    extern float BuildingUpgradeDescriptionFontSize;
    extern float BuildingInformationAccentFontSize;
    extern float BuildingInformationBodyFontSize;
    extern float BuildingBudgetButtonFontSize;
    extern float BuildingActionButtonFontSize;
    extern float BuildingOverviewCommandButtonFontSize;
    extern float BuildingTitleIconInsetX;
    extern float BuildingTitleIconOffsetY;
    extern float BuildingTitleTextInsetX;
    extern float BuildingTitleIconGap;
    extern float BuildingTitleTextOffsetX;
    extern float BuildingTitleTextOffsetY;
    extern float BuildingTitleTextWidthAdjust;
    extern float BuildingTitleTextHeightAdjust;
    extern float BuildingSubtitleOffsetY;
    extern float BuildingTitleRibbonOffsetX;
    extern float BuildingTitleRibbonOffsetY;
    extern float BuildingTitleRibbonHeight;
    extern float BuildingSectionRibbonHeight;
    extern float BuildingSectionRibbonOffsetY;
    extern float BuildingCollapsedSectionGap;
    extern float BuildingCloseButtonOffsetX;
    extern float BuildingCloseButtonOffsetY;
    extern float BuildingCloseButtonSize;
    extern float BuildingCompactControlHeight;
    extern float BuildingCompactBudgetButtonWidth;
    extern float BuildingSectionDividerWidth;
    extern float BuildingSectionDividerHeight;
    extern float BuildingBudgetBaseOffsetY;
    extern float BuildingBudgetLabelOffsetY;
    extern float BuildingBudgetCustomButtonsOffsetY;
    extern float BuildingBudgetWorkButtonsOffsetY;
    extern float BuildingBudgetDefaultButtonsOffsetY;
    extern float BuildingBudgetCompactGap;
    extern float BuildingBudgetDefaultGap;
    extern float BuildingModeButtonHeight;
    extern float BuildingModeButtonGap;
    extern float BuildingOccupancyGapY;
    extern float BuildingActionButtonHeight;
    extern float BuildingActionButtonWidth;
    extern float BuildingActionButtonBottomMargin;
    extern float BuildingActionCompactIconSize;
    extern float BuildingActionCompactIconOffsetY;
    extern float BuildingMoveCompactRightOffset;
    extern float BuildingFocusCompactRightOffset;
    extern float BuildingOverviewCommandGap;
    extern float BuildingMinimumTabStartInset;
    extern float BuildingCustomOverviewMetricRowHeight;
    extern float BuildingWorkOverviewMetricRowHeight;
    extern float BuildingCompactMetricRowHeight;
    extern float BuildingBudgetButtonHeight;
    extern float BuildingScrollTrackWidth;
    extern float BuildingScrollBottomInset;
    extern float BuildingScrollThumbHeight;
    extern float BuildingScrollThumbTopOffset;
    extern float BuildingBodyGapAfterSection;
    extern float BuildingBodyGapAfterActions;
    extern float BuildingBodyGapBeforeActions;
    extern float BuildingBodyFallbackOffset;
    extern float BuildingBodyBottomInset;
    extern float BuildingIconSize;

    // ── NPC 선택 UI ──────────────────────────────────────────
    extern float CitizenPanelWidthRatio;
    extern float CitizenPanelMinWidth;
    extern float CitizenPanelMaxWidth;
    extern float CitizenPanelTopOffset;
    extern float CitizenPanelBottomMargin;
    extern float CitizenPanelRightInset;
    extern float CitizenPanelMinHeight;
    extern float CitizenPanelInnerMarginX;
    extern float CitizenPanelInnerTopOffset;
    extern float CitizenPanelInnerBottomInset;
    extern float CitizenTitleFontSize;
    extern float CitizenSubtitleFontSize;
    extern float CitizenBodyFontSize;
    extern float CitizenPageTitleFontSize;
    extern float CitizenTitleRibbonHeight;
    extern float CitizenSectionRibbonHeight;
    extern float CitizenSectionRibbonOffsetY;
    extern float CitizenScrollTrackWidth;
    extern float CitizenScrollBottomInset;
    extern float CitizenScrollThumbHeight;
    extern float CitizenScrollThumbTopOffset;
    extern float CitizenCloseButtonSize;
    extern float CitizenCloseButtonOffsetY;
    extern float CitizenBudgetBaseOffsetY;
    extern float CitizenActionStackTopOffset;
    extern float CitizenFooterBottomInset;
    extern float CitizenBodyBottomInset;

    namespace CitizenInfoLayoutDefaults
    {
        constexpr float TitleIconInsetX = 6.f;
        constexpr float TitleIconOffsetY = 0.f;
        constexpr float TitleTextInsetX = 14.f;
        constexpr float TitleTextOffsetX = 0.f;
        constexpr float TitleTextOffsetY = 0.f;
        constexpr float TitleTextWidthAdjust = 0.f;
        constexpr float TitleTextHeightAdjust = 0.f;
        constexpr float TitleIconGap = 6.f;
        constexpr float SubtitleOffsetY = 4.f;
        constexpr float CollapsedSectionGap = 6.f;
        constexpr float BudgetLabelOffsetY = 2.f;
        constexpr float BudgetCustomButtonsOffsetY = 20.f;
        constexpr float BudgetWorkButtonsOffsetY = 78.f;
        constexpr float BudgetDefaultButtonsOffsetY = 26.f;
        constexpr float BudgetCompactGap = 6.f;
        constexpr float BudgetDefaultGap = 8.f;
        constexpr float OccupancyGapY = 18.f;
        constexpr float CompactControlHeight = 22.f;
        constexpr float CompactBudgetButtonWidth = 36.f;
        constexpr float SectionDividerWidth = 172.f;
        constexpr float SectionDividerHeight = 14.f;
        constexpr float ActionButtonHeight = 38.f;
        constexpr float ActionGap = 4.f;
        constexpr float ActionCompactIconSize = 34.f;
        constexpr float ActionCompactIconOffsetY = 2.f;
        constexpr float ActionIconInset = 8.f;
        constexpr float MoveCompactRightOffset = 82.f;
        constexpr float FocusCompactRightOffset = 40.f;
        constexpr float OverviewCommandGap = 10.f;
        constexpr float BodyGapAfterSection = 8.f;
        constexpr float BodyGapAfterActions = 14.f;
        constexpr float BodyGapBeforeActions = 12.f;
        constexpr float BodyFallbackOffset = 4.f;
    }

    namespace TradeWidgetLayout
    {
        constexpr float ScreenMargin = 120.f;
        constexpr float MinimumAvailableWidth = 640.f;
        constexpr float MinimumAvailableHeight = 560.f;
        constexpr float HeaderHeight = 62.f;
        constexpr float TitleWidthRatio = 0.42f;
        constexpr float PageButtonWidth = 132.f;
        constexpr float PageButtonHeight = 34.f;
        constexpr float PageButtonGap = 12.f;
        constexpr float PageButtonTopOffset = 14.f;
        constexpr float PageButtonTextFontSize = 15.f;
        constexpr float TitleRibbonTopOffset = 8.f;
        constexpr float CloseButtonSize = 36.f;
        constexpr float SectionGap = 18.f;
        constexpr float LeftPanelRatio = 0.52f;
        constexpr float RightPanelGap = 48.f;
        constexpr float LeftPanelInset = 26.f;
        constexpr float ContentTopOffset = 20.f;
        constexpr float ContentBottomInset = 48.f;
        constexpr float FilterHeight = 44.f;
        constexpr float SortHeight = 34.f;
        constexpr float CompletionAutoOpenButtonWidth = 150.f;
        constexpr float CompletionAutoOpenButtonGap = 14.f;
        constexpr float RouteListTopOffset = 12.f;
        constexpr float FilterToSortGap = 10.f;
        constexpr float ListFrameFilterOffset = 8.f;
        constexpr float RowHeight = 46.f;
        constexpr float RowGap = 6.f;
        constexpr float TitleTextInsetX = 18.f;
        constexpr float TitleTextHorizontalPadding = 36.f;
        constexpr float TitleFontSize = 30.f;
        constexpr float CountdownRightOffset = 280.f;
        constexpr float CountdownTopOffset = 18.f;
        constexpr float CountdownWidth = 214.f;
        constexpr float CountdownHeight = 28.f;
        constexpr float CountdownFontSize = 15.f;
        constexpr float CloseButtonRightOffset = 52.f;
        constexpr float CloseButtonTopOffset = 12.f;
        constexpr float FilterButtonWidth = 194.f;
        constexpr float FilterTextFontSize = 16.f;
        constexpr float SortButtonGap = 8.f;
        constexpr float SortButtonTextFontSize = 15.f;
        constexpr float RowTextFontSize = 15.f;
        constexpr float ResourceTextFontSize = 16.f;
        constexpr float DirectionColumnWidth = 72.f;
        constexpr float ActiveRoutePartnerWidth = 108.f;
        constexpr float ProductPricePartnerWidth = 118.f;
        constexpr float DefaultPartnerWidth = 120.f;
        constexpr float ActiveRouteMarginWidth = 150.f;
        constexpr float ProductPriceMarginWidth = 120.f;
        constexpr float DefaultMarginWidth = 84.f;
        constexpr float ResourceColumnsHorizontalPadding = 48.f;
        constexpr float ProposalButtonInsetX = 10.f;
        constexpr float ProposalButtonHorizontalPadding = 20.f;
        constexpr float PriceModifierFirstSectionTop = 66.f;
        constexpr float PriceModifierSecondSectionTop = 256.f;
        constexpr float PriceModifierThirdSectionTop = 508.f;
        constexpr float PriceModifierSecondSectionTitleTop = 212.f;
        constexpr float PriceModifierThirdSectionTitleTop = 464.f;
        constexpr float PriceModifierRowGap = 8.f;
        constexpr float ProposalDirectionInsetX = 12.f;
        constexpr float ProposalPartnerInsetX = 18.f;
        constexpr float PriceModifierResourceInsetX = 20.f;
        constexpr float ProposalResourceInsetX = 24.f;
        constexpr float ProposalMarginInsetX = 26.f;
        constexpr float PriceModifierResourceRightOffset = 156.f;
        constexpr float PriceModifierMarginLeftOffset = 136.f;
        constexpr float PriceModifierMarginWidth = 112.f;
        constexpr float SectionTitleLeftInset = 10.f;
        constexpr float SectionTitleRightInset = 28.f;
        constexpr float LeftSectionTitleHorizontalPadding = 32.f;
        constexpr float SectionTitleHeight = 28.f;
        constexpr float SectionTitleFontSize = 18.f;
        constexpr float DetailTitleInsetX = 28.f;
        constexpr float DetailTitleTopOffset = 16.f;
        constexpr float DetailTitleHorizontalPadding = 56.f;
        constexpr float DetailTitleHeight = 34.f;
        constexpr float DetailTitleFontSize = 22.f;
        constexpr float DetailLabelWidth = 150.f;
        constexpr float DetailValueHorizontalPadding = 68.f;
        constexpr float DetailRowHeight = 28.f;
        constexpr float PriceModifierDetailStartTop = 254.f;
        constexpr float DefaultDetailStartTop = 70.f;
        constexpr float DetailRowGap = 34.f;
        constexpr float PriceModifierDetailLabelRightOffset = 180.f;
        constexpr float PriceModifierDetailValueLeftOffset = 136.f;
        constexpr float PriceModifierDetailValueWidth = 108.f;
        constexpr float DetailValueFontSize = 17.f;
        constexpr float AmountTitleTopOffset = 402.f;
        constexpr float AmountTitleWidth = 130.f;
        constexpr float AmountTitleHeight = 28.f;
        constexpr float AmountTitleFontSize = 17.f;
        constexpr float TwoColumnAmountHorizontalPadding = 66.f;
        constexpr float ThreeColumnAmountHorizontalPadding = 76.f;
        constexpr float AmountButtonGap = 10.f;
        constexpr float AmountButtonTopOffset = 438.f;
        constexpr float AmountButtonHeight = 40.f;
        constexpr float AmountButtonTextFontSize = 15.f;
        constexpr float ActionButtonTopOffset = 496.f;
        constexpr float ActionButtonHeight = 46.f;
        constexpr float ActionButtonTextFontSize = 18.f;
        constexpr float CompletionAutoOpenButtonTopOffset = 548.f;
        constexpr float CompletionAutoOpenButtonHeight = 40.f;
        constexpr float FeedbackRightPadding = 28.f;
        constexpr float FeedbackTopOffsetModifiers = 56.f;
        constexpr float FeedbackTopOffsetCompleted = 552.f;
        constexpr float FeedbackTopOffsetDefault = 558.f;
        constexpr float FeedbackHeightModifiers = 112.f;
        constexpr float FeedbackHeightCompleted = 72.f;
        constexpr float FeedbackHeightDefault = 124.f;
    }
}

namespace UILayoutValues = UIConfig;
